# Generated by Django 6.0.4 on 2026-04-22 22:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('surveys', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], db_index=True, default='draft', max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
                ('respondent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='surveys.survey')),
            ],
            options={
                'db_table': 'responses_response',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_key', models.CharField(db_index=True, max_length=64)),
                ('value_json', models.JSONField(blank=True, null=True)),
                ('value_encrypted', models.TextField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='responses.response')),
            ],
            options={
                'db_table': 'responses_answer',
                'ordering': ['response_id', 'field_key'],
            },
        ),
        migrations.AddIndex(
            model_name='response',
            index=models.Index(fields=['organization', 'survey', 'status'], name='responses_r_organiz_57ec58_idx'),
        ),
        migrations.AddIndex(
            model_name='response',
            index=models.Index(fields=['organization', 'submitted_at'], name='responses_r_organiz_e8ca27_idx'),
        ),
        migrations.AddConstraint(
            model_name='response',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'draft')), fields=('organization', 'survey', 'respondent'), name='uniq_draft_per_survey_respondent'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['organization', 'field_key'], name='responses_a_organiz_fa1753_idx'),
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('response', 'field_key'), name='uniq_answer_per_response_key'),
        ),
    ]
