# Generated by Django 6.0.4 on 2026-04-21 01:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('survey_group_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('version', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
            ],
            options={
                'db_table': 'surveys_survey',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('visible_when', models.JSONField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='surveys.survey')),
            ],
            options={
                'db_table': 'surveys_section',
                'ordering': ['survey_id', 'position'],
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=64)),
                ('position', models.PositiveIntegerField()),
                ('type', models.CharField(max_length=32)),
                ('label', models.CharField(max_length=200)),
                ('help_text', models.TextField(blank=True, default='')),
                ('required', models.BooleanField(default=False)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('visible_when', models.JSONField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='surveys.section')),
            ],
            options={
                'db_table': 'surveys_field',
                'ordering': ['section_id', 'position'],
                'constraints': [models.UniqueConstraint(fields=('section', 'position'), name='uniq_field_section_position')],
            },
        ),
        migrations.AddIndex(
            model_name='survey',
            index=models.Index(fields=['organization', 'status'], name='surveys_sur_organiz_614e5e_idx'),
        ),
        migrations.AddIndex(
            model_name='survey',
            index=models.Index(fields=['organization', 'survey_group_id'], name='surveys_sur_organiz_87d926_idx'),
        ),
        migrations.AddConstraint(
            model_name='survey',
            constraint=models.UniqueConstraint(fields=('organization', 'survey_group_id', 'version'), name='uniq_survey_group_version'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('survey', 'position'), name='uniq_section_survey_position'),
        ),
    ]
