# Generated by Django 6.0.4 on 2026-04-22 22:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_email', models.EmailField(blank=True, default='', max_length=254)),
                ('role', models.CharField(blank=True, default='', max_length=16)),
                ('method', models.CharField(max_length=8)),
                ('path', models.CharField(max_length=512)),
                ('status_code', models.PositiveSmallIntegerField()),
                ('request_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='organizations.organization')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', '-created_at'], name='audit_log_organiz_27eb85_idx'), models.Index(fields=['user', '-created_at'], name='audit_log_user_id_b57afc_idx'), models.Index(fields=['method', 'path'], name='audit_log_method_07f8dd_idx')],
            },
        ),
    ]
